//Login

export const loginTypes = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERR0R',
  LOGIN_USERNAME: 'LOGIN_USERNAME',
  LOGIN_PASSWORD: 'LOGIN_PASSWORD',
  LOGOUT: 'LOGOUT'
}

export const newUserTypes = {
  NEW_USERNAME: 'NEW_USERNAME',
  NEW_PASSWORD: 'NEW_PASSWORD',
  CONFIRMED_PASSWORD: 'CONFIRMED_PASSWORD',
  ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
  ADD_USER_ERROR: 'ADD_USER_ERROR'
}

//Remove a user
export const removeUserTypes = {
  REMOVE_USER_SUCCESS: 'REMOVE_USER_SUCCESS',
  REMOVE_USER_ERROR: 'REMOVE_USER_ERROR'
}

//Get decklist from database
export const decklistTypes = {
  GET_DECKLIST_SUCCESS: 'GET_DECKLIST_SUCCESS',
  GET_DECKLIST_ERROR: 'GET_DECKLIST_ERROR',
  UPDATE_DECKLIST: 'UPDATE_DECKLIST'
}

export const deckTypes = {
  DECK_NAME: 'DECK_NAME',
  DECK_FORMAT: 'DECK_FORMAT',
  DECK_IS_ACTIVE: 'DECK_IS_ACTIVE',
  ADD_DECK_SUCCESS: 'ADD_DECK_SUCCESS',
  ADD_DECK_ERROR: 'ADD_DECK_ERROR',
  REMOVE_DECK_SUCCESS: 'REMOVE_DECK_SUCCESS',
  REMOVE_DECK_ERROR: 'REMOVE_DECK_ERROR',
  SELECT_DECK: 'SELECT_DECK',
  UPDATE_DECK: 'UPDATE_DECK',
  DECK_SEARCH_SUCCESS: 'DECK_SEARCH_SUCCESS',
  DECK_SEARCH_ERROR: 'DECK_SEARCH_ERROR'
}

export const cardTypes = {
  ADD_CARD_SUCCESS: 'ADD_CARD_SUCCESS',
  ADD_CARD_ERROR: 'ADD_CARD_ERROR',
  REMOVE_CARD_SUCCESS: 'REMOVE_CARD_SUCCESS',
  REMOVE_CARD_ERROR: 'REMOVE_CARD_ERROR',
  CARD_SEARCH_SUCCESS: 'CARD_SEARCH_SUCCESS',
  CARD_SEARCH_ERROR: 'CARD_SEARCH_ERROR',
  PAGE_FORWARD: 'PAGE_FORWARD',
  PAGE_BACK: 'PAGE_BACK'
}

export const filterTypes = {
  FILTER_RESET: 'FILTER_RESET',
  NAME_FILTER: 'NAME_FILTER',
  CMC_FILTER: 'CMC_FILTER',
  TYPE_FILTER: 'TYPE_FILTER',
  RARITY_FILTER: 'RARITY_FILTER',
  COLOR_FILTER: 'COLOR_FILTER',
  REMOVE_COLOR_FILTER: 'REMOVE_COLOR_FILTER',
  COLORS_TO_STRING: 'COLORS_TO_STRING'
}